### ISSUE TITLE
Don't hardcode the response

### ISSUE THREAD

**Issue by karthikb351** [viveksmits/savetheinternet#1]
Fixing errors and/or updating the content of that letter will now require an update to the app. Instead see if you can pull the website down and scrape the letter from there? It's plainly visible in the source code. That way it will always reflect what the site reflects.

Another hack would be to run the website in a hidden webview, inject a javascript interface and listen to the 'generateResponse' method being called. That will give you the response directly.

**Comment by viveks7** [comment]
I initially did that. Didn't know the response where random. Trying to resolve. :)

**Comment by viveks7** [comment]
Issue is now solved. Now response are fetched from website. New apk will be published soon.
